### ISSUE TITLE
request: setting locale parameter on search

### ISSUE THREAD

**Issue by MorganOlufsen** [webeweb/pexels-library#1]
Pexels API has a parameter **locale** to set the language of query searches:
https://www.pexels.com/api/documentation/#photos-search__locale

I think that no method is implemented to set this parameter.
Or at least it doesn't appear in the docs.

**Comment by webeweb** [comment]
Hi

I updated the library with the new features.
Can you tell me if this new version fixes the problems encountered?

Best regards
