### ISSUE TITLE
Can't install package on the latest version of Laravel

### ISSUE THREAD

**Issue by Alejandro-AP00** [webeweb/pexels-library#3]
Currently, this library uses Guzzle ^6.0 but Laravel 8 is using Guzzle ^7.0
Is there a way to install it regardless?  `composer require webeweb/pexels-library --with-all-dependencies` does not  work either.

**Comment by webeweb** [comment]
Please, try the new release 2.2.0 and tell me if this new release fix your issue

**Comment by Alejandro-AP00** [comment]
It does! Thank you!

**Comment by webeweb** [comment]
You're welcome

Best regards
