### ISSUE TITLE
search by color

### ISSUE THREAD

**Issue by bertrandcouturier** [webeweb/pexels-library#5]
Hello,

What about :
ArrayHelper::set($result, "color", $request->getColor());
in serializeSearchPhotosRequest() ?

Best regards

**Comment by webeweb** [comment]
Hi,

Can you test the color attribute with the master branch version ?

Awaiting your reply

**Comment by bertrandcouturier** [comment]
Now, it works,
Thank you for the fix, and your lib, by the way

**Comment by webeweb** [comment]
You're welcome.

I have release the version 2.5 which contains the last fixes.

Best regards
