### ISSUE TITLE
PHP FTP extension Warning

### ISSUE THREAD

**Issue by luxorwannabe** [webeweb/pexels-library#6]
Hi,

Firstly nice Library :)

FYI I get composer error says: `require ext-ftp * -> it is missing from your system. Install or enable PHP's ftp extension.`

How to integrate this https://github.com/phpseclib/phpseclib so our end users no need to enable the FTP extension?

**Comment by webeweb** [comment]
Hi,

The PHP extension is needed by the `core-library` dependency which contains a FTP/FTPS/SFTP client.
Unfortunately, I don't see any other solution than to install the PHP FTP extension.

Best regards
